version: "3.9"

services:
  images-service:
    build: .
    container_name: images-service
    env_file:
      - .env
    ports:
      - "${UVICORN_PORT:-8000}:${UVICORN_PORT:-8000}"
    volumes:
      - ./static:/app/static
    restart: unless-stopped
