services:
  images:
    build: .
    container_name: images
    env_file:
      - .env
    expose:
      - "${UVICORN_PORT:-8000}"
    restart: unless-stopped
    networks:
      - unidev_app-unidev

networks:
  unidev_app-unidev:
    external: true